# to make importing easier
from .circ_stats import *
from .classification import *
from .correlation import *
from .dim_reduction import *
from .feature_selection import *
from .func_conn import *
from .generic import *
from .masking import *
from .matrices import *
from .model_selection import *
from .mvpa import *
from .nonparametric import *
from .patterns import *
from .plotting import *
from .quality import *
from .regression import *
from .standard_modules import *
from .statistics import *